#!/usr/bin/env node
import { execFileSync } from 'node:child_process'
import { mkdirSync, writeFileSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { extractTranslations, parseDiff, type TranslationPair, type UnmatchedLine } from './extract.ts'
import { supplementalTranslations } from './supplemental.ts'

const COMMIT = 'b07016d'
const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '../..')
// The glossary diff and individual source files must fit without truncating child-process output.
const MAX_GIT_OUTPUT_BYTES = 32 * 1024 * 1024

/** Runs a read-only git command with bounded output and contextual error reporting. */
function git(args: string[]): string {
  try {
    return execFileSync('git', args, { cwd: ROOT, encoding: 'utf8', maxBuffer: MAX_GIT_OUTPUT_BYTES })
  } catch (err) {
    console.error('[extract-from-fork] 失敗', { context: { operation: 'git', args }, err })
    throw err
  }
}

/** Creates an output directory and writes a generated UTF-8 artifact with contextual failures. */
function writeArtifact(path: string, content: string): void {
  try {
    const absolutePath = resolve(ROOT, path)
    mkdirSync(dirname(absolutePath), { recursive: true })
    writeFileSync(absolutePath, content, 'utf8')
  } catch (err) {
    console.error('[extract-from-fork] 失敗', { context: { operation: 'write', path }, err })
    throw err
  }
}

/**
 * Serializes machine-extracted entries and reviewed entries without losing either on reruns.
 *
 * The fork commit this extracts from was machine-translated, so some of its strings are wrong
 * (mistranslated product names, broken grammar, literal renderings). A reviewed entry therefore
 * *overrides* the extracted one for the same key rather than colliding with it; extraction only
 * supplies the baseline. Overrides are reported by `countOverrides` so a silent shadowing of a
 * key that no longer exists upstream stays visible.
 */
function renderDictionary(pairs: TranslationPair[], locale: 'en' | 'ja'): string {
  const entries: string[] = []
  for (const pair of pairs) {
    const reviewed = supplementalTranslations[pair.key]
    entries.push(`  ${JSON.stringify(pair.key)}: ${JSON.stringify((reviewed ?? pair)[locale])},`)
  }
  const extracted = new Set(pairs.map(pair => pair.key))
  entries.push('  // Reviewed additions for UI introduced after the localization commit.')
  for (const [key, pair] of Object.entries(supplementalTranslations)) {
    if (extracted.has(key)) continue
    entries.push(`  ${JSON.stringify(key)}: ${JSON.stringify(pair[locale])},`)
  }
  return `// Generated by node scripts/i18n/extract-from-fork.ts from ${COMMIT}; do not edit directly.\nconst messages: Record<string, string> = {\n${entries.join('\n')}\n}\n\nexport default messages\n`
}

/** Escapes source lines for an HTML preformatted block without breaking the Markdown report. */
function escapeReport(value: string): string {
  return value.replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;')
}

/** Lists every rejected old/new line and the exact reason it requires human review. */
function renderReport(pairs: TranslationPair[], unmatched: UnmatchedLine[], matchedLines: number, totalRemoved: number, totalAdded: number): string {
  const removed = unmatched.filter(line => line.side === 'removed').length
  const added = unmatched.filter(line => line.side === 'added').length
  const sections = [
    '# Japanese localization extraction report',
    '',
    `Source: \`git diff ${COMMIT}^..${COMMIT}\`. Regenerate with \`node scripts/i18n/extract-from-fork.ts\`.`,
    '',
    `- Total translation pairs extracted: **${pairs.length}**`,
    `- Matched positional line pairs: **${matchedLines}**`,
    `- Changed lines: **${totalRemoved} removed / ${totalAdded} added**`,
    `- Unmatched lines: **${removed} removed / ${added} added**`,
    `- Supplemental entries (not extracted): **${Object.keys(supplementalTranslations).length}**`,
    '',
    'Each contiguous change run is paired positionally within its hunk. Only literal contents may differ; surrounding code, whitespace, delimiters, and literal kinds must match. JSX text is decoded as display text. Comments, interpolated templates, multiline quoted literals, structural edits, and non-Japanese replacements are never guessed. Repeated literals receive numeric key suffixes.',
    '',
    '1691 insertions/deletions describe changed lines, not a guaranteed number of string literals. A line can contain several literals or no safely extractable literal.',
    '',
    'Removed locations refer to the parent commit; added locations refer to the localization commit. To fill gaps, add reviewed entries to `scripts/i18n/supplemental.ts` and rerun the generator; the unmatched source evidence remains in this report.',
    '',
    '## Unmatched lines',
  ]
  for (const line of unmatched) {
    sections.push('', `### ${line.side}: ${line.file}:${line.line}`, '', line.reason, '', `<pre>${escapeReport(line.text)}</pre>`)
  }
  return `${sections.join('\n')}\n`
}

/** Extracts the localization glossary and writes both dictionaries and the review report. */
function main(): void {
  console.log(`[extract-from-fork] Reading ${COMMIT} diff`)
  const blocks = parseDiff(git(['diff', '--no-ext-diff', '--no-textconv', '--no-color', `${COMMIT}^..${COMMIT}`]))
  const files = new Set(blocks.flatMap(block => [...block.removed, ...block.added].map(line => line.file)))
  const sources = new Map<string, { before: string; after: string }>()
  for (const file of files) {
    console.log(`[extract-from-fork] Parsing ${file}`)
    sources.set(file, { before: git(['show', `${COMMIT}^:${file}`]), after: git(['show', `${COMMIT}:${file}`]) })
  }
  const { pairs, unmatched, matchedLines } = extractTranslations(blocks, sources)
  const totalRemoved = blocks.reduce((count, block) => count + block.removed.length, 0)
  const totalAdded = blocks.reduce((count, block) => count + block.added.length, 0)
  writeArtifact('packages/i18n/src/locales/en.ts', renderDictionary(pairs, 'en'))
  writeArtifact('packages/i18n/src/locales/ja.ts', renderDictionary(pairs, 'ja'))
  writeArtifact('scripts/i18n/extract-report.md', renderReport(pairs, unmatched, matchedLines, totalRemoved, totalAdded))
  console.log(`[extract-from-fork] Extracted ${pairs.length} translation pairs from ${matchedLines} line pairs; unmatched ${unmatched.filter(line => line.side === 'removed').length} removed / ${unmatched.filter(line => line.side === 'added').length} added lines`)

  // A reviewed key that no longer matches anything upstream is dead weight the report should
  // surface, since the fork commit is fixed but the source files it patched keep moving.
  const extracted = new Set(pairs.map(pair => pair.key))
  const reviewed = Object.keys(supplementalTranslations)
  const overrides = reviewed.filter(key => extracted.has(key))
  console.log(`[extract-from-fork] Reviewed entries: ${overrides.length} override extracted strings, ${reviewed.length - overrides.length} add new keys`)
}

main()
