/**
 * The worker's bindings. `Env` (generated by `pnpm types:generate` from wrangler.jsonc) covers the
 * declared bindings; secrets are set per deployment and so are declared here.
 */
export type PhotosEnv = Env & {
  /** 32 random bytes, base64. Encrypts storage credentials; required. */
  PHOTOS_CREDENTIAL_KEY?: string;
  /** Set (by scripts/deploy.sh) only when Cloudflare Access does not front the deployment. */
  PHOTOS_DIRECT_SHARE?: string;
};

/** Hono context variables set by the request middleware. */
export interface PhotosVariables {
  /** The administrator the request acts for, as recorded in created_by / updated_by. */
  actor: string;
}

/** Hono environment for every Photos route. */
export interface PhotosHono {
  Bindings: PhotosEnv;
  Variables: PhotosVariables;
}
